export enum TechCategory {
  FRONTEND = 'FRONTEND',
  BACKEND = 'BACKEND',
  BUILD_MANAGEMENT = 'BUILD_MANAGEMENT',
  DATABASE = 'DATABASE',
  CICD = 'CICD',
  VERSION_CONTROL = 'VERSION_CONTROL',
  CONTAINERS = 'CONTAINERS',
  CLOUD = 'CLOUD',
  MOBILE = 'MOBILE',
  STREAM = 'STREAM',
  AGILE = 'AGILE',
  OTHER = 'OTHER'
}
